return {
  { "mileszs/ack.vim" },
  { "jlanzarotta/bufexplorer" },
  { "preservim/nerdtree" },
  { "vim-scripts/nginx.vim" },
  { "amix/open_file_under_cursor.vim" },
  { "MarcWeber/vim-addon-mw-utils" },
  { "tomtom/tlib_vim" },
  { "garbas/vim-snipmate",
    dependencies = "MarcWeber/vim-addon-mw-utils"
  },
  { "scrooloose/snipmate-snippets" },
  { "sophacles/vim-bundle-mako" },
  { "altercation/vim-colors-solarized" },
  { "michaeljsmith/vim-indent-object" },
  { "groenewege/vim-less" },
  { "tpope/vim-surround" },
  { "terryma/vim-expand-region" },
  { "mg979/vim-visual-multi" },
  { "tpope/vim-fugitive" },
  { "vim-airline/vim-airline",
    dependecies = { "vim-airline/vim-airline-themes" }
  },
  { "vim-airline/vim-airline-themes" },
  { "junegunn/goyo.vim" },
  { "amix/vim-zenroom2" },
  { "scrooloose/syntastic" },
  { "tpope/vim-repeat" },
  { "tpope/vim-commentary" },
  { "airblade/vim-gitgutter" },
  { "morhetz/gruvbox" },
  { "Shougo/deoplete.nvim", build = vim.fn.has("nvim") == 1 and ":UpdateRemotePlugins" or nil },
  { "roxma/nvim-yarp", cond = vim.fn.has("nvim") == 0 },
  { "roxma/vim-hug-neovim-rpc", cond = vim.fn.has("nvim") == 0 },
  { "carlitux/deoplete-ternjs", build = "npm install -g tern" },
  { "kana/vim-textobj-user" },
  { "beloglazov/vim-textobj-quotes",
    dependencies = { "kana/vim-textobj-user" }
  },
  { "pangloss/vim-javascript" },
  { "maxmellon/vim-jsx-pretty" },
  { "iamcco/markdown-preview.nvim" },
  { "prettier/vim-prettier", build = "npm install --force" },
  { "kevinhwang91/nvim-hlslens" },
  { "nvim-lua/plenary.nvim" },
  { "CopilotC-Nvim/CopilotChat.nvim" },
  { "nvim-telescope/telescope.nvim", tag = "0.1.4" },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
}

